### PR TITLE
Add support for matching dependencies

### PR DESCRIPTION
**Pull request by philipp94831**
I followed the steps in the wiki.
Furthermore, I will file a pull request for the frontend repository.

I needed to bump the jersey version in order to have a more recent version of jackson.
I did not detect any problems with the newer version.
I also updated fastutil.

### CODE REVIEW

**Comment by maxifischer** [comment]
Hi Philipp, most of the PR looks good already, but the new algorithm is not appearing in the algorithm types of the Frontend so far. I added a few minor changes to the Wiki in that regard. You might want to double check that the algorithm is in algorithm_integrations/results/Result, the toString in Algorithm, the algorithm.description of new.controller.js and fully implemented in result.html. If you have the time check your algorithm with a testing algorithm. I hope that helps

**Comment by philipp94831** [comment]
I tested it locally and everything works. I will have a look at it again. I think that I had similar behavior at first but rebuilding or something like that helped

**Comment by philipp94831** [comment]
@maxifischer Hi, I cleanly built Metanome on a different machine and everything worked. Did you checkout the correct backend branch (feature/mds)? Did you also pull the correct frontend repo?

**Comment by maxifischer** [comment]
Works for me now

**Pull request merged**
